library(shiny)
library(bslib)
library(childesr)
library(tidyverse)
library(ggplot2)
library(feather)
library(RColorBrewer)
library(purrr)
library(yaml)

source("styling.R")
source("data.R")
source("literature.R")
source("plots.R")

shinyApp(ui = ui, server = server)
